# Generated by Django 4.2.5 on 2023-12-20 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_en_us',
            new_name='name_en',
        ),
    ]
