# Generated by Django 4.2.5 on 2023-12-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
        migrations.AddField(
            model_name='feedback',
            name='phone_number',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
